### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by jhamman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jhamman** [comment]
@conda-forge-admin, please rerender

**Comment by andersy005** [comment]
```bash
ModuleNotFoundError: No module named 'cachey'
```

It looks like cachey is missing from the list of dependencies. Do you know why things previously worked without cachey being listed as a dependency?

**Review by andersy005 — APPROVED** [review]
Looks great! 👍

**Comment by jhamman** [comment]
> It looks like cachey is missing from the list of dependencies. Do you know why things previously worked without cachey being listed as a dependency?

I think it was just missing from the prior version of the recipe. In prior versions of xpublish, it was more encapsulated and wasn't imported automatically.

**Pull request merged**
